apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextcloud.fullname" . }}-scripts
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
data:
  initdb.sh: |
    #!/bin/bash
    sleep {{ .Values.settings.databaseUpdateDelay }}
    php occ db:add-missing-indices
    php occ db:add-missing-columns
    php occ db:convert-filecache-bigint
