apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-internal
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: client
      name: client
    - port: {{ .Values.service.peer.port }}
      targetPort: peer
      name: peer
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
