{{- if and .Values.userDatabase }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}-inituserdb
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  init-user-db.sh: |-
    mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD <<EOF
      var userdb = db.getSiblingDB('$MONGO_INITDB_DATABASE');
      userdb.createUser({user: '$USERDB_USER', pwd: '$USERDB_PASSWORD', roles: [ "readWrite", "dbAdmin" ]});
    EOF
{{- end }}
