apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
stringData:
  {{- if .Values.userDatabase }}
  MONGO_INITDB_DATABASE: {{ .Values.userDatabase.name | quote }}
  {{- end }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.settings.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.settings.rootPassword | default (randAlphaNum 10) | quote }}
