{{- if and .Values.replicaSet.enabled .Values.replicaSet.arbiter.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongodb.fullname" . }}-arbiter
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    service-type: arbiter
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.customAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mongodb.selectorLabels" . | nindent 6 }}
      service-type: arbiter
  serviceName: {{ include "mongodb.fullname" . }}-{{ .Values.replicaSet.arbiter.headlessServiceSuffix }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: 1
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  updateStrategy: 
    type: {{ .Values.updateStrategyType }}  
  template:
    metadata:
      annotations:
        checksum/customconfig: {{ include (print $.Template.BasePath "/customconfig.yaml") . | sha256sum }}
        checksum/secureconfig: {{ include (print $.Template.BasePath "/secureconfig.yaml") . | sha256sum }}
        checksum/scripts: {{ include (print $.Template.BasePath "/scripts.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb.selectorLabels" . | nindent 8 }}
        service-type: arbiter
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mongodb.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- if .Values.extraSecretConfigs }}
            - mountPath: /extraconfigs
              name: extraconfigs-volume
            {{- end }}
            {{- if .Values.customConfig }}
            - mountPath: /customconfig
              name: customconfig-volume
            {{- end }}
            - mountPath: /extrainitscripts
              name: extrainitscripts
            - mountPath: /scripts
              name: scripts
            - mountPath: /configs
              name: configs
            - mountPath: /replicaset
              name: keyfile
            {{- if .Values.replicaSet.keySecretName }}
            - mountPath: /keyfile-secret
              name: keyfile-secret
            {{- end }}
          command: [ "/scripts/init.sh" ]
      {{- with .Values.extraInitContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/extrainitscripts/extra-init.sh" ]
          args:
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
            - --config
            - /etc/mongo/custom.conf
            - --replSet 
            - {{ .Values.replicaSet.name | quote }}
            - --keyFile
            - "/replicaset/keyfile"
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          {{- if .Values.customStartupProbe }}
          startupProbe:
            {{- toYaml .Values.customStartupProbe | nindent 12 }}
          {{- else }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /extrainitscripts/mongoshell --eval "db.adminCommand('ping')"
          {{- with .Values.startupProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
            periodSeconds: {{ .periodSeconds }}                
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.customLivenessProbe }}
          livenessProbe:
            {{- toYaml .Values.customLivenessProbe | nindent 12 }}
          {{- else }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /extrainitscripts/mongoshell --eval "db.adminCommand('ping')"
          {{- with .Values.livenessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.customReadinessProbe }}
          readinessProbe:
            {{- toYaml .Values.customReadinessProbe | nindent 12 }}
          {{- else }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /extrainitscripts/mongoshell --eval "db.adminCommand('ping')"
          {{- with .Values.readinessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.replicaSet.arbiter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if include "mongodb.createSecureConfig" . }}
            - secretRef:
                name: {{ include "mongodb.fullname" . }}
            {{- end }}
            {{- range .Values.extraEnvSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          env:
            - name: "MONGOTYPE"
              value: "ARBITER"
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: extrainitscripts
              mountPath: /extrainitscripts
            - name: {{ .Values.replicaSet.arbiter.storage.volumeName }}
              mountPath: /data/db
            - mountPath: /etc/mongo
              name: configs
            - mountPath: /replicaset
              name: keyfile
            {{- range $secret := .Values.extraSecrets }}
            - name: {{ $secret.name }}
              mountPath: {{ $secret.mountPath }}
            {{- end }}
      {{- with .Values.extraContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replicaSet.arbiter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replicaSet.arbiter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replicaSet.arbiter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replicaSet.arbiter.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: extrainitscripts
          emptyDir: {}
        - name: configs
          emptyDir: {}
        - name: keyfile
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ include "mongodb.fullname" . }}-scripts
            defaultMode: 0555
        {{- if .Values.extraSecretConfigs }}
        - name: extraconfigs-volume
          secret:
            secretName: {{ .Values.extraSecretConfigs }}
        {{- end }}
        {{- if .Values.customConfig }}
        - name: customconfig-volume
          configMap:
            name: {{ include "mongodb.fullname" . }}-customconfig
        {{- end }}
        {{- range $secret := .Values.extraSecrets }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.name }}
            defaultMode: 0440
        {{- end }}
        {{- if and .Values.replicaSet.enabled .Values.replicaSet.keySecretName }}
        - name: keyfile-secret
          secret:
            secretName: {{ .Values.replicaSet.keySecretName }}
            defaultMode: 0400
        {{- end }}
{{- with .Values.replicaSet.arbiter.storage }}
  {{- $createPvc := and (empty .persistentVolumeClaimName) .requestedSize }}
  {{- if not $createPvc }}
        - name: {{ .volumeName }}
        {{- if .persistentVolumeClaimName }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaimName }}
        {{- else }}
          emptyDir: {}
        {{- end }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .volumeName }}
      {{- with .labels }}
        labels:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .annotations }}
        annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      spec:
        {{- with .accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .className }}
        storageClassName: {{ .className }}
        {{- end }}
        resources:
          requests:
            storage: {{ .requestedSize }}
  {{- end }}
{{- end }}
{{- end }}
