{{- if .Values.initGeoIPDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graylog.fullname" . }}-geoip
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
type: Opaque
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.initGeoIPDatabase.accountId | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.initGeoIPDatabase.licenseKey | b64enc }}
  GEOIPUPDATE_EDITION_IDS: {{ .Values.initGeoIPDatabase.editionId | b64enc }}
  {{- if .Values.initGeoIPDatabase.proxyUserPassword }}
  GEOIPUPDATE_PROXY_USER_PASSWORD: {{ .Values.initGeoIPDatabase.proxyUserPassword | b64enc }}
  {{- end }}
{{- end }}
