{{- if .Values.initGeoIPDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graylog.fullname" . }}-geoip
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
stringData:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.initGeoIPDatabase.accountId | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.initGeoIPDatabase.licenseKey | quote }}
  GEOIPUPDATE_EDITION_IDS: {{ .Values.initGeoIPDatabase.editionId | quote }}
  {{- if .Values.initGeoIPDatabase.host }}
  GEOIPUPDATE_HOST: {{ .Values.initGeoIPDatabase.host | quote }}
  {{- end }}
  {{- if .Values.initGeoIPDatabase.proxy }}
  GEOIPUPDATE_PROXY: {{ .Values.initGeoIPDatabase.proxy | quote }}
  {{- end }}
  {{- if .Values.initGeoIPDatabase.proxyUserPassword }}
  GEOIPUPDATE_PROXY_USER_PASSWORD: {{ .Values.initGeoIPDatabase.proxyUserPassword | quote }}
  {{- end }}
{{- end }}
