apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graylog.fullname" . }}-scripts
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
data:
  init.sh: |
    #!/bin/bash
    echo "Initializing Graylog..."
    if [ ! -f /data/config/graylog.conf ]; then
      echo "No Graylog configuration found - Initializing directory structure"
      mkdir -p /data/config
      mkdir -p /data/journal
      mkdir -p /data/log
      mkdir -p /data/plugin
      mkdir -p /data/contentpacks
      echo "Copy configuration"
      cp /usr/share/graylog/data/config/* /data/config
    else
      echo "Graylog configuration already exists."
    fi
    echo "Setting permissions on configuration folder"
    chmod u+rw /data/config/*
    echo "Finished."
