apiVersion: v1
kind: Service
metadata:
  name: {{ include "graylog.fullname" . }}-internal
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graylog.selectorLabels" . | nindent 4 }}
