apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}-internal
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.transportPort }}
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
