replicaCount: 1

## Ingress configuration
ingress:
  enabled: true

  ## Maximal body size (default: 64m - increase if uploads to gitea failing)
  maxBodySize: 64m

  annotations:
    cert-manager.io/cluster-issuer: local-ca

  hosts:
    - host: dev.k8.local
      paths:
        - /
  tls:
    - secretName: dev-k8-local
      hosts:
        - dev.k8.local

## Internal container HTTP port (default: 8000)
containerHttpPort: 8000
## Internal container SSH port (default: 8022)
containerSshPort: 8022


## Gitea specific configuration as described in https://docs.gitea.io/en-us/config-cheat-sheet/
gitea:
  config:
    APP_NAME: "Home Git"
    server:
      PROTOCOL: http
      ROOT_URL: https://dev.k8.local

## Gitea storage parameters
storage:
  ## Set persistentVolumenClaimName to reference an existing PVC
  # persistentVolumeClaimName: <own-pvc-name>

  ## Alternative set requestedSize to define a size for a dynmaically created PVC
  requestedSize: 64Mi

  ## the storage class name
  # className:

  ## Default access mode (ReadWriteOnce)
  accessModes:
    - ReadWriteOnce

## MariaDB configuration
mariadb:
  ## Enable MariaDB helm chart for deployment (default: false)
  enabled: false

  ## Database configuration
  settings:
    ## Database startup arguments (enable UTF8MB4 and Unicode support)
    arguments:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    ## The root user password (default: a 10 char. alpahnumerical random password will be generated)
    rootPassword:

  ## Optional user database which is created during first startup with user and password
  userDatabase:
    ## Name of the user database
    name:
    ## Database user with full access rights
    user:
    ## Password of the database user (default: a 10 char. alpahnumerical random password will be generated)
    password:

  # Storage parameters
  storage:
    ## Set persistentVolumenClaimName to reference an existing PVC
    # persistentVolumeClaimName: <own-pvc-name>

    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    # requestedSize: <volume-size>

    ## the storage class name
    # className:

## PostgreSQL configuration
postgres:
  ## Enable PostgreSQL helm chart for deployment (default: false)
  enabled: true

  ## Database configuration
  settings:

    ## The superuser password (default: a 10 char. alpahnumerical random password will be generated)
    superuserPassword:

  ## User database which is created during first startup with user and password
  userDatabase:
    ## Database name
    name: gitea
    ## Database user
    user: giteadbuser
    ## Database password (default: 10 alphanum. random characters)
    password: giteadbpasswd

  # Storage parameters
  storage:
    ## Set persistentVolumenClaimName to reference an existing PVC
    # persistentVolumeClaimName: <own-pvc-name>

    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    requestedSize: 64Mi

    ## the storage class name
    # className:

## Redis configuration
redis:
  ## Enable Redis helm chart for deployment (default: false)
  enabled: false

  # Storage parameters
  storage:
    ## Set persistentVolumenClaimName to reference an existing PVC
    # persistentVolumeClaimName: <own-pvc-name>

    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    # requestedSize: <volume-size>

    ## the storage class name
    # className:
