{{- if .Values.customInlineScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-customscripts
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.customInlineScripts }}
  {{- $name | nindent 2 }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
