{{- if .Values.userDatabase }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-inituserdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
{{- with .Values.userDatabase }}
  init-user-db.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -v USERDBNAME="$USERDB_NAME" -v USERDBUSER="$USERDB_USER" -v USERDBPASSWORD="'$USERDB_PASSWORD'" <<-EOSQL
      CREATE USER :USERDBUSER WITH PASSWORD :USERDBPASSWORD;
      CREATE DATABASE :USERDBNAME;
      GRANT ALL PRIVILEGES ON DATABASE :USERDBNAME TO :USERDBUSER;
    EOSQL
{{- end }}
{{- end }}
