{{- if include "postgres.createSecureConfig" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.settings }}
  {{- if .superuser }}
  POSTGRES_USER: {{ .superuser | b64enc }}
  {{- end }}
  {{- if .superuserPassword }}
  POSTGRES_PASSWORD: {{ .superuserPassword | b64enc }}
  {{- end }}
{{- end }}
{{- with .Values.userDatabase }}
  POSTGRES_DB: {{ required "Values: userDatabase.name is mandatory if userDatabase is specified." .name | b64enc }}
  {{- if .user }}
  USERDB_USER: {{ .user | b64enc }}
  USERDB_PASSWORD: {{ required "Values: userDatabase.password is mandatory if userDatabase.user is specified." .password | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
