apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
stringData:
{{- with .Values.settings }}
  POSTGRES_PASSWORD: {{ .superuserPassword | default (randAlphaNum 10) }}
  POSTGRES_USER: "postgres"
  POSTGRES_HOST_AUTH_METHOD: {{ .authMethod }}
{{- end }}
{{- with .Values.userDatabase }}
  USERDB_PASSWORD: {{ .password | default (randAlphaNum 10) }}
  USERDB_USER: {{ .user }}
  USERDB_NAME: {{ .name }}
{{- end }}
