{{- if .Values.redisConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    {{- .Values.redisConfig | nindent 4 }}
{{- end }}
