apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commento.fullname" . }}
  labels:
    {{- include "commento.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.postgres.enabled }}
  COMMENTO_POSTGRES: postgres://{{ .Values.postgres.userDatabase.user }}:{{ .Values.postgres.userDatabase.password }}@{{ include "postgres.servicename" . }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.userDatabase.name }}?sslmode=disable
{{- else }}
{{- with .Values.externalDatabase }}
  COMMENTO_POSTGRES: postgres://{{ .user }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .name }}?sslmode=disable
{{- end }}
{{- end }}
{{- with .Values.settings.smtp }}
  {{- if .enabled }}
  COMMENTO_SMTP_HOST: {{ .host }}
  COMMENTO_SMTP_PORT: {{ .port | quote }}
  COMMENTO_SMTP_USERNAME: {{ .name }}
  COMMENTO_SMTP_PASSWORD: {{ .password | quote }}
  COMMENTO_SMTP_FROM_ADDRESS: {{ .from }}
  {{- end }}
{{- end }}
{{- if .Values.settings.akismetKey }}
  COMMENTO_AKISMET_KEY: {{ .Values.settings.akismetKey | quote }}
{{- end }}
{{- with .Values.settings.oauth }}
  {{- if .google.enabled }}
  COMMENTO_GOOGLE_KEY: {{ .google.key | quote }}
  COMMENTO_GOOGLE_SECRET: {{ .google.secret | quote }}
  {{- end }}
  {{- if .github.enabled }}
  COMMENTO_GITHUB_KEY: {{ .github.key | quote }}
  COMMENTO_GITHUB_SECRET: {{ .github.secret | quote }}
  {{- end }}
  {{- if .gitlab.enabled }}
  COMMENTO_GITLAB_KEY: {{ .gitlab.key | quote }}
  COMMENTO_GITLAB_SECRET: {{ .gitlab.secret | quote }}
  {{- end }}
  {{- if .twitter.enabled }}
  COMMENTO_TWITTER_KEY: {{ .twitter.key | quote }}
  COMMENTO_TWITTER_SECRET: {{ .twitter.secret | quote }}
  {{- end }}      
{{- end }}