apiVersion: v1
kind: Service
metadata:
  name: {{ template "codimd.fullname" . }}
  labels:
    app.kubernetes.io/component: Service
    {{ include "codimd.labels" . | nindent 4 }}
  {{ if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  {{ if (and (eq .Values.service.type "LoadBalancer") .Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{ end }}
  {{ if (and (eq "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP | quote }}
  {{ end }}
  selector:
    app.kubernetes.io/component: server
    {{- include "codimd.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000