{{ if .Values.codimd.security.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "codimd.shortName" . }}-session
  labels:
    app.kubernetes.io/component: sessionSecret
    {{ include "codimd.labels" . | nindent 4 }}
stringData:
  CMD_SESSION_SECRET: {{ .Values.codimd.security.sessionSecret | quote }}
{{ end }}