apiVersion: v2
name: mysql
description: A Helm chart for MySQL on Kubernetes

type: application

maintainers:
  - name: groundhog2k
    url: https://github.com/groundhog2k/helm-charts

keywords:
  - database
  - mysql

version: "1.0.0"

appVersion: "8.0.35"
