apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.settings.rootPassword | default (randAlphaNum 10) }}
{{- with .Values.userDatabase }}
  MYSQL_DATABASE: {{ .name }}
  MYSQL_USER: {{ .user }}
  MYSQL_PASSWORD: {{ .password | default (randAlphaNum 10) }}
{{- end }}