{{- $rootSet := and (not .Values.settings.existingSecret) ((.Values.settings.rootPassword).value) }}
{{- $userDatabaseSet := and (.Values.userDatabase) (not .Values.userDatabase.existingSecret) }}
{{- if or ($rootSet) ($userDatabaseSet) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.settings }}
  {{- if (.rootPassword).value }}
  MARIADB_ROOT_PASSWORD: {{ .rootPassword.value | b64enc }}
  {{- end }}
  {{- end }}
  {{- with .Values.userDatabase }}
  {{- if not .existingSecret }}
  {{- $_ := required "Values: userDatabase.name is mandatory if userDatabase is specified without existing secret" .name }}
  MARIADB_DATABASE: {{ required "Values: userDatabase.name.value is mandatory if userDatabase is specified without existingSecret." .name.value | b64enc }}
  {{- if (.user).value }}
  MARIADB_USER: {{ .user.value | b64enc }}
  {{- $_ := required "Values: userDatabase.password is mandatory if userDatabase is specified without existing secret" .password }}
  MARIADB_PASSWORD: {{ required "Values: userDatabase.password.value is mandatory if userDatabase.user is specified without existingSecret." .password.value | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
