apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}-internal
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sql
      protocol: TCP
      name: sql
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
