{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.serviceAccountName" . }}
  labels: 
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ include "rabbitmq.fullname" . }}
{{- end }}
