{{- if .Values.customScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-customscripts
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.customScripts }}
  {{- $name | nindent 2 }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
