{{- with .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ghost.fullname" $ }}
spec:
  podSelector:
    matchLabels:
      {{- include "ghost.selectorLabels" $ | nindent 6 }}
  policyTypes:
  {{- if .ingress }}
    - Ingress
  {{- end }}
  {{- if .egress }}
    - Egress
  {{- end }}
  {{- with .ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
