replicaCount: 2

nodeSelector:
  kubernetes.io/arch: amd64

ingress:
  enabled: true

  annotations:
    cert-manager.io/cluster-issuer: local-ca

  hosts:
    - host: rabbitmq.k8.local
      paths:
        - /
  tls:
    - secretName: rabbitmq-k8-local
      hosts:
        - rabbitmq.k8.local

resources:
  limits:
    memory: 300Mi

options:
  memoryHighWatermark:
    enabled: true
    type: "relative"
    value: 0.9

authentication:
  user: admin
  password: admin
  erlangCookie: "bXljb29raWVpc2hvdA"

storage:
  requestedSize: 128Mi
