name: Release helm chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run Release
        uses: helm/chart-releaser-action@master
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
